### ISSUE TITLE
`found` documentation has inputs reversed

### ISSUE THREAD

**Issue by jaredkrinke** [GordonCharlton/Quackery#12]
In The Book:

> found ( a b --> c ) ... found expects a nest, a, and a number, b

But the definition assumes the nest is on top:

```
[ size < ]                    is found        (     n [ --> b       )
```

The stack effects comment doesn't make sense to me, as well.

Edit to add: the foreword in your book is great!

**Comment by GordonCharlton** [comment]
Good catch. Thank you. Description corrected.
