### ISSUE TITLE
Inconsistent `forward` usage across the documentation

### ISSUE THREAD

**Issue by olus2000** [GordonCharlton/Quackery#5]
In the **BUILDERS** section of the Quackery Quick Reference the example for `forward` contradicts The Book of Quackery and the actual implementation. The example goes like this:
```
forward name - makes a forward
               reference
```
While the actual usage is:
```
forward is name - makes a forward
                  reference
```

In addition to that there is a nonsensical problem listed under "Compilation Problems" on page 35 of The Book of Quackery:
```
"forward" needs a name after it.
```
Clearly, `forward` doesn't need a name after it.

### Followup question
This issue is just an excuse to ask: why is `forward` a builder? All it does is append a constant nest to the nest being built, which is exactly what a normal name does at build-time. What's so special about `forward`?

**Comment by olus2000** [comment]
Only after going and trying to change `forward` to a normal name I realised what I have missed. `forward` doesn't just append a constant nest to the building nest, it appends *a new copy* of `[ undefined ]`, which later allows `resolves` to replace `undefined` with the actual behaviour without mutating the `actions` table.

I'm just a little butthurt that my adventofcode solution is not as pretty as I wanted it to be.

**Comment by GordonCharlton** [comment]
Amendment noted.

Sorry about my recent unresponsiveness. November was complicated. Nothing bad or sad, just stuff that required immediate attention. December will probably be the same, but by January I should be able to attend to amendments.

**Comment by olus2000** [comment]
Of course. My college is also gaining pace, so if it wasn't for the Advent of Code I wouldn't be touching Quackery until the holidays.
