### ISSUE TITLE
errors in TBoQ

### ISSUE THREAD

**Issue by dragoncoder047** [GordonCharlton/Quackery#7]
page 28 - word named `undeal`, but subsequent paragraph says `undealall`

page 49 - says "build in data structure" - shouldn't it be "buil**t** in"?

also, if #6 is merged the errors on pages 33 and after will have to be fixed.

**Comment by GordonCharlton** [comment]
done, done and done. Pushing updated TBoQ now...

**Comment by dragoncoder047** [comment]
Sorry to bother you again...

page 60: `(pronounced meta-done”)` missing open quote

page 61: second test of `lights` (to 5) still would print out `There are four lights.` shouldn't it be `five`?

page 101: the output of the `takefile` test isn't lined up with the `...`s - looks as if there is a hidden `9 emit` on each line (9 being `tab`)

**Comment by GordonCharlton** [comment]
Again thank you. Done, not done, done.

;-)
![IMG_0008](https://user-images.githubusercontent.com/75318677/165893479-80379a3a-0aff-4203-91f7-ceeff960fb4b.GIF)

**Comment by GordonCharlton** [comment]
(Also, the ancillary stack `lights` still contains `4` at that point, so evaluating `lights share 5 = ' [ say "There are four lights." cr ] 'if` does _not_ print "`There are four lights.`" — it's illustrating that `'if` does nothing if ToS is `false`.)

**Comment by dragoncoder047** [comment]
Sorry for necroposting, found another error.

Page 11 - very bottom - you defined `edges` and then did `3 4 5 volume` again.

**Comment by GordonCharlton** [comment]
Good catch. Thank you. Fixed.

**Comment by dragoncoder047** [comment]
page 61 - `... lights share 5 = ' [`... shouldn't the first prompt be `/O>`?

page 62 - missed 'jump'

> As with `'if`, we will start the definition with `nested`, not only for consistency, but because the nest it finds on the stack could have words like `while` and `done` in it, which rely on the end of the nest not having stuff arbitrarily added to it, as they **jump** right to the end of the nest, wherever it is.

**Comment by GordonCharlton** [comment]
Fixed, thank you.
